//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
[System.Xml.Serialization.XmlRootAttribute("competition", Namespace="http://www.divecalc.net/ns/diving", IsNullable=false)]
public partial class Competition {
    
    private Text titleField;
    
    private Text placeField;
    
    private Team[] teamsField;
    
    private Participant[] participantsField;
    
    private Official[] officialsField;
    
    private Events eventsField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string uidField;
    
    /// <remarks/>
    public Text title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public Text place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("team", IsNullable=false)]
    public Team[] teams {
        get {
            return this.teamsField;
        }
        set {
            this.teamsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("participant", IsNullable=false)]
    public Participant[] participants {
        get {
            return this.participantsField;
        }
        set {
            this.participantsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("official", IsNullable=false)]
    public Official[] officials {
        get {
            return this.officialsField;
        }
        set {
            this.officialsField = value;
        }
    }
    
    /// <remarks/>
    public Events events {
        get {
            return this.eventsField;
        }
        set {
            this.eventsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Text {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class OtherEvent {
    
    private Text titleField;
    
    private Text descriptionField;
    
    private Time starttimeField;
    
    private Time endtimeField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string idField;
    
    /// <remarks/>
    public Text title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public Text description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-time")]
    public Time starttime {
        get {
            return this.starttimeField;
        }
        set {
            this.starttimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("end-time")]
    public Time endtime {
        get {
            return this.endtimeField;
        }
        set {
            this.endtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Time {
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class LinkedEvents {
    
    private Event[] eventField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("event")]
    public Event[] @event {
        get {
            return this.eventField;
        }
        set {
            this.eventField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Event {
    
    private Text titleField;
    
    private EventSeries seriesField;
    
    private Time starttimeField;
    
    private Time endtimeField;
    
    private JudgePanel[] judgepanelField;
    
    private Diver[] diversField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string idField;
    
    private bool preliminaryField;
    
    private bool finalField;
    
    private bool synchroField;
    
    public Event() {
        this.preliminaryField = false;
        this.finalField = false;
        this.synchroField = false;
    }
    
    /// <remarks/>
    public Text title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public EventSeries series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-time")]
    public Time starttime {
        get {
            return this.starttimeField;
        }
        set {
            this.starttimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("end-time")]
    public Time endtime {
        get {
            return this.endtimeField;
        }
        set {
            this.endtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("judge-panel")]
    public JudgePanel[] judgepanel {
        get {
            return this.judgepanelField;
        }
        set {
            this.judgepanelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("diver", IsNullable=false)]
    public Diver[] divers {
        get {
            return this.diversField;
        }
        set {
            this.diversField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool preliminary {
        get {
            return this.preliminaryField;
        }
        set {
            this.preliminaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool final {
        get {
            return this.finalField;
        }
        set {
            this.finalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool synchro {
        get {
            return this.synchroField;
        }
        set {
            this.synchroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.divecalc.net/ns/diving")]
public partial class EventSeries {
    
    private bool menField;
    
    private bool menFieldSpecified;
    
    private bool womenField;
    
    private bool womenFieldSpecified;
    
    private bool onemField;
    
    private bool onemFieldSpecified;
    
    private bool threemField;
    
    private bool threemFieldSpecified;
    
    private bool platformField;
    
    private bool platformFieldSpecified;
    
    private string minageField;
    
    private string maxageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool men {
        get {
            return this.menField;
        }
        set {
            this.menField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool menSpecified {
        get {
            return this.menFieldSpecified;
        }
        set {
            this.menFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool women {
        get {
            return this.womenField;
        }
        set {
            this.womenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool womenSpecified {
        get {
            return this.womenFieldSpecified;
        }
        set {
            this.womenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("one-m")]
    public bool onem {
        get {
            return this.onemField;
        }
        set {
            this.onemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool onemSpecified {
        get {
            return this.onemFieldSpecified;
        }
        set {
            this.onemFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("three-m")]
    public bool threem {
        get {
            return this.threemField;
        }
        set {
            this.threemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool threemSpecified {
        get {
            return this.threemFieldSpecified;
        }
        set {
            this.threemFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool platform {
        get {
            return this.platformField;
        }
        set {
            this.platformField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool platformSpecified {
        get {
            return this.platformFieldSpecified;
        }
        set {
            this.platformFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("min-age", DataType="integer")]
    public string minage {
        get {
            return this.minageField;
        }
        set {
            this.minageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("max-age", DataType="integer")]
    public string maxage {
        get {
            return this.maxageField;
        }
        set {
            this.maxageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class JudgePanel {
    
    private Judge[] judgeField;
    
    private System.Xml.XmlElement[] anyField;
    
    private judgepanel panelField;
    
    private string[] roundsField;
    
    public JudgePanel() {
        this.panelField = judgepanel.A;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("judge")]
    public Judge[] judge {
        get {
            return this.judgeField;
        }
        set {
            this.judgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(judgepanel.A)]
    public judgepanel panel {
        get {
            return this.panelField;
        }
        set {
            this.panelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string[] rounds {
        get {
            return this.roundsField;
        }
        set {
            this.roundsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Judge : IdRef {
    
    private string judgeField;
    
    private judgetype typeField;
    
    public Judge() {
        this.typeField = judgetype.A;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string judge {
        get {
            return this.judgeField;
        }
        set {
            this.judgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(judgetype.A)]
    public judgetype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="judge-type", Namespace="http://www.divecalc.net/ns/diving")]
public enum judgetype {
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    B,
    
    /// <remarks/>
    synchro,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DiverParticipant))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Judge))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class IdRef {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class DiverParticipant : IdRef {
    
    private diver diverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public diver diver {
        get {
            return this.diverField;
        }
        set {
            this.diverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public enum diver {
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    B,

    C,

    D
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="judge-panel", Namespace="http://www.divecalc.net/ns/diving")]
public enum judgepanel {
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    B,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Diver {
    
    private DiverParticipant[] participantField;
    
    private Integer positionField;
    
    private DiveList divelistField;
    
    private DiverResults resultsField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("participant")]
    public DiverParticipant[] participant {
        get {
            return this.participantField;
        }
        set {
            this.participantField = value;
        }
    }
    
    /// <remarks/>
    public Integer position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dive-list")]
    public DiveList divelist {
        get {
            return this.divelistField;
        }
        set {
            this.divelistField = value;
        }
    }
    
    /// <remarks/>
    public DiverResults results {
        get {
            return this.resultsField;
        }
        set {
            this.resultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Integer {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class DiveList {
    
    private Dive[] diveField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dive")]
    public Dive[] dive {
        get {
            return this.diveField;
        }
        set {
            this.diveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Dive {
    
    private System.Xml.XmlElement[] anyField;
    
    private string numberField;
    
    private diver diverField;
    
    private string diveField;
    
    private height heightField;
    
    private decimal ddField;
    
    private decimal syncroddField;
    
    private bool syncroddFieldSpecified;
    
    private diver positionField;
    
    private bool positionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public diver diver {
        get {
            return this.diverField;
        }
        set {
            this.diverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string dive {
        get {
            return this.diveField;
        }
        set {
            this.diveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public height height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal dd {
        get {
            return this.ddField;
        }
        set {
            this.ddField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("syncro-dd")]
    public decimal syncrodd {
        get {
            return this.syncroddField;
        }
        set {
            this.syncroddField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool syncroddSpecified {
        get {
            return this.syncroddFieldSpecified;
        }
        set {
            this.syncroddFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public diver position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool positionSpecified {
        get {
            return this.positionFieldSpecified;
        }
        set {
            this.positionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public enum height {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7.5")]
    Item75,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class DiverResults {
    
    private Rank rankField;
    
    private Result startresultField;
    
    private Result finalresultField;
    
    private DiveResult[] diveresultsField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    public Rank rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-result")]
    public Result startresult {
        get {
            return this.startresultField;
        }
        set {
            this.startresultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("final-result")]
    public Result finalresult {
        get {
            return this.finalresultField;
        }
        set {
            this.finalresultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("dive-results")]
    [System.Xml.Serialization.XmlArrayItemAttribute("dive", IsNullable=false)]
    public DiveResult[] diveresults {
        get {
            return this.diveresultsField;
        }
        set {
            this.diveresultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Rank {
    
    private rankstatus statusField;
    
    private string rankField;
    
    private bool qualifiedField;
    
    private bool qualifiedFieldSpecified;
    
    public Rank() {
        this.statusField = rankstatus.normal;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(rankstatus.normal)]
    public rankstatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool qualified {
        get {
            return this.qualifiedField;
        }
        set {
            this.qualifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qualifiedSpecified {
        get {
            return this.qualifiedFieldSpecified;
        }
        set {
            this.qualifiedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="rank-status", Namespace="http://www.divecalc.net/ns/diving")]
public enum rankstatus {
    
    /// <remarks/>
    normal,
    
    /// <remarks/>
    aborted,
    
    /// <remarks/>
    disqualified,
    
    /// <remarks/>
    outside,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Result {
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class DiveResult {
    
    private DiveAwards awardsField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string numberField;
    
    private decimal sumField;
    
    private decimal resultField;
    
    private decimal totalField;
    
    /// <remarks/>
    public DiveAwards awards {
        get {
            return this.awardsField;
        }
        set {
            this.awardsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal sum {
        get {
            return this.sumField;
        }
        set {
            this.sumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class DiveAwards {
    
    private DiveAward[] awardField;
    
    private DivePenalty[] penaltyField;
    
    private DivePenalty[] maximumField;
    
    private DiveAwardsFailed[] failedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("award")]
    public DiveAward[] award {
        get {
            return this.awardField;
        }
        set {
            this.awardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("penalty")]
    public DivePenalty[] penalty {
        get {
            return this.penaltyField;
        }
        set {
            this.penaltyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("maximum")]
    public DivePenalty[] maximum {
        get {
            return this.maximumField;
        }
        set {
            this.maximumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("failed")]
    public DiveAwardsFailed[] failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class DiveAward {
    
    private string awardField;
    
    private string judgeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string award {
        get {
            return this.awardField;
        }
        set {
            this.awardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string judge {
        get {
            return this.judgeField;
        }
        set {
            this.judgeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class DivePenalty {
    
    private string awardField;
    
    private diver positionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string award {
        get {
            return this.awardField;
        }
        set {
            this.awardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public diver position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.divecalc.net/ns/diving")]
public partial class DiveAwardsFailed {
    
    private bool failedField;
    
    private diver positionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public diver position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class EventSet {
    
    private Text nameField;
    
    private object[] itemsField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string idField;
    
    /// <remarks/>
    public Text name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("event", typeof(Event))]
    [System.Xml.Serialization.XmlElementAttribute("linked-events", typeof(LinkedEvents))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Events {
    
    private object[] itemsField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("event", typeof(Event))]
    [System.Xml.Serialization.XmlElementAttribute("event-set", typeof(EventSet))]
    [System.Xml.Serialization.XmlElementAttribute("other", typeof(OtherEvent))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Official {
    
    private Text firstnameField;
    
    private Text lastnameField;
    
    private IdRef teamField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string idField;
    
    private string uidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("first-name")]
    public Text firstname {
        get {
            return this.firstnameField;
        }
        set {
            this.firstnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-name")]
    public Text lastname {
        get {
            return this.lastnameField;
        }
        set {
            this.lastnameField = value;
        }
    }
    
    /// <remarks/>
    public IdRef team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Participant {
    
    private Text firstnameField;
    
    private Text lastnameField;
    
    private IdRef teamField;
    
    private IdRef secondaryteamField;
    
    private Integer birthyearField;
    
    private Integer birthmonthField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string idField;
    
    private string uidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("first-name")]
    public Text firstname {
        get {
            return this.firstnameField;
        }
        set {
            this.firstnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-name")]
    public Text lastname {
        get {
            return this.lastnameField;
        }
        set {
            this.lastnameField = value;
        }
    }
    
    /// <remarks/>
    public IdRef team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("secondary-team")]
    public IdRef secondaryteam {
        get {
            return this.secondaryteamField;
        }
        set {
            this.secondaryteamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("birth-year")]
    public Integer birthyear {
        get {
            return this.birthyearField;
        }
        set {
            this.birthyearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("birth-month")]
    public Integer birthmonth {
        get {
            return this.birthmonthField;
        }
        set {
            this.birthmonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.divecalc.net/ns/diving")]
public partial class Team {
    
    private Text nameField;
    
    private Text shortnameField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string idField;
    
    private string uidField;
    
    /// <remarks/>
    public Text name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("short-name")]
    public Text shortname {
        get {
            return this.shortnameField;
        }
        set {
            this.shortnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}
